/*  =========================================================================
    test - generated layer of public API

    Copyright (c) the Authors

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef TEST_LIBRARY_H_INCLUDED
#define TEST_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>

//  TEST version macros for compile-time API detection
#define TEST_VERSION_MAJOR 0
#define TEST_VERSION_MINOR 1
#define TEST_VERSION_PATCH 0

#define TEST_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define TEST_VERSION \
    TEST_MAKE_VERSION(TEST_VERSION_MAJOR, TEST_VERSION_MINOR, TEST_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined TEST_STATIC
#       define TEST_EXPORT
#   elif defined TEST_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define TEST_EXPORT __declspec(dllexport)
#       else
#           define TEST_EXPORT
#       endif
#   elif defined TEST_EXPORTS
#       define TEST_EXPORT __declspec(dllexport)
#   else
#       define TEST_EXPORT __declspec(dllimport)
#   endif
#   define TEST_PRIVATE
#else
#   define TEST_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define TEST_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define TEST_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  TEST_BUILD_DRAFT_API
#define TEST_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef TEST_BUILD_DRAFT_API
typedef struct _test1_t test1_t;
#define TEST1_T_DEFINED
#endif // TEST_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef TEST_BUILD_DRAFT_API
#include "test1.h"
#endif // TEST_BUILD_DRAFT_API

#ifdef TEST_BUILD_DRAFT_API
//  Self test for private classes
TEST_EXPORT void
    test_private_selftest (bool verbose);
#endif // TEST_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
