/*  =========================================================================
    test_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef TEST_CLASSES_H_INCLUDED
#define TEST_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/test.h"

//  Extra headers

//  Opaque class structures to allow forward references
#ifndef TEST2_T_DEFINED
typedef struct _test2_t test2_t;
#define TEST2_T_DEFINED
#endif

//  Internal API
#include "test2.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef TEST_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
TEST_PRIVATE void
    test2_test (bool verbose);

//  Self test for private classes
TEST_PRIVATE void
    test_private_selftest (bool verbose);

#endif // TEST_BUILD_DRAFT_API

#endif
